CREATE TABLE "TOPCATEGORY" (
   "TOP_ID"   VARCHAR2(20)      NOT NULL,
   "DOC_ID"   VARCHAR2(20)      NOT NULL,
   "TOP_CODE"   VARCHAR2(30)      NULL,
   "TOP_NAME"   VARCHAR2(30)      NULL,
   "TOP_STEP"   VARCHAR2(100)      NULL,
   "TOP_DELFLAG"   CHAR(1)      NULL,
   "TOP_DATE"   DATE      NULL
);


CREATE TABLE "PROJMEMLIST" (
   "MEM_ID"   VARCHAR2(16)      NULL,
   "PROJ_NAME"   VARCHAR2(100)      NOT NULL,
   "PROJ_PM"   CHAR(1)      NULL
);

CREATE TABLE "MEMBERLIST" (
   "MEMBER_ID"   VARCHAR2(16)      NOT NULL,
   "MEM_NAME"   VARCHAR2(30)      NULL,
   "MEM_PW"   VARCHAR2(1000)      NULL,
   "MEM_ADDR"   VARCHAR2(200)      NULL,
   "MEM_BIRTH"   VARCHAR2(15)      NULL,
   "MEM_PHONE"   VARCHAR2(15)      NULL,
   "MEM_EMAIL"   VARCHAR2(40)      NOT NULL
);

CREATE TABLE "NOTIFICATION" (
   "NOTI_ID"   VARCHAR2(20)      NOT NULL,
   "PROJ_NAME"   VARCHAR2(100)      NOT NULL,
   "MEM_ID"   VARCHAR2(16)      NULL,
   "NOTI_CONTENT"   VARCHAR2(100)      NULL,
   "NOTI_NOTIFIDED"   CHAR(1)      NULL,
   "NOTI_REGDATE"   DATE      NULL
);

CREATE TABLE "PROJECT" (
   "PROJ_NAME"   VARCHAR2(100)      NOT NULL,
   "PROJ_TOKEN"   VARCHAR2(30)      NULL
);

CREATE TABLE "FBS" (
   "MID_ID"   VARCHAR2(20)      NOT NULL,
   "TOP_ID"   VARCHAR2(20)      NOT NULL,
   "FBS_NAME"   VARCHAR2(30)      NULL,
   "FBS_CODE"   VARCHAR2(30)      NULL,
   "FBS_CONTENT"   VARCHAR2(100)      NULL,
   "FBS_IMP"   CHAR(1)      NULL,
   "FBS_LEVEL"   CHAR(1)      NULL,
   "FBS_MANAGER"   VARCHAR2(30)      NULL,
   "FBS_STEP"   NUMBER     NULL,
   "FBS_DELFLAG"   CHAR(1)      NULL,
   "FBS_DATE"   DATE      NULL
);


CREATE TABLE "WBS" (
   "WBS_ID"   VARCHAR2(20)      NOT NULL,
   "MID_ID"   VARCHAR2(20)      NOT NULL,
   "WBS_CODE"   VARCHAR2(10)      NULL,
   "WBS_NAME"   VARCHAR2(50)      NULL,
   "WBS_CONENT"   VARCHAR2(500)      NULL,
   "WBS_MANAGER"   VARCHAR2(30)      NULL,
   "WBS_START_DATE"   VARCHAR2(20)      NULL,
   "WBS_END_DATE"   VARCHAR2(20)      NULL,
   "WBS_FIN_DATE"   VARCHAR2(20) DEFAULT ' ',
   "WBS_STEP"   NUMBER      NULL,
   "WBS_DELFLAG"   CHAR(1)      NULL,
   "WBS_DATE"   DATE      NULL
);

CREATE TABLE "DOCUMENT" (
   "DOC_ID"   VARCHAR2(20)      NOT NULL,
   "PROJ_NAME"   VARCHAR2(100)      NOT NULL,
   "DOC_DATE"   DATE      NULL
);


CREATE TABLE "FIXHISTORY" (
   "FIX_ID"   VARCHAR2(20)      NOT NULL,
   "DOC_ID"   VARCHAR2(20)      NOT NULL,
   "FIX_CONTENT"   VARCHAR2(1000)      NULL,
   "FIX_NAME"   VARCHAR2(20)      NULL,
   "FIX_DATE"   DATE      NULL
);

CREATE TABLE SCHEDULE(
	SCHE_ID VARCHAR2(20) NOT NULL,
	MEM_ID VARCHAR2(16),
	SCHE_NAME VARCHAR2(20),
	SCHE_CONTENT VARCHAR2(100),
	SCHE_START VARCHAR2(30),
	SCHE_END VARCHAR2(30)
);

ALTER TABLE 테이블명
ADD CONSTRAINT 제약조건명
  FOREIGN KEY (CHILD_테이블의_FK값)
  REFERENCES MOTHER_테이블명(MOTHER_테이블의_PK)
  ON DELETE CASCADE;


ALTER TABLE "TOPCATEGORY" ADD CONSTRAINT "PK_TOPCATEGORY" PRIMARY KEY (
   "TOP_ID"
);

ALTER TABLE "PROJMEMLIST" ADD CONSTRAINT "PK_PROJMEMLIST" PRIMARY KEY (
   "MEM_ID"
);

ALTER TABLE "MEMBERLIST" ADD CONSTRAINT "PK_MEMBERLIST" PRIMARY KEY (
   "MEMBER_ID"
);

ALTER TABLE "PROJECT" ADD CONSTRAINT "PK_PROJECT" PRIMARY KEY (
   "PROJ_NAME"
);

ALTER TABLE "FBS" ADD CONSTRAINT "PK_FBS" PRIMARY KEY (
   "MID_ID"
);

ALTER TABLE "WBS" ADD CONSTRAINT "PK_WBS" PRIMARY KEY (
   "WBS_ID"
);

ALTER TABLE "DOCUMENT" ADD CONSTRAINT "PK_DOCUMENT" PRIMARY KEY (
   "DOC_ID"
);

ALTER TABLE "FIXHISTORY" ADD CONSTRAINT "PK_FIXHISTORY" PRIMARY KEY (
   "FIX_ID"
);

ALTER TABLE "SCHEDULE" ADD CONSTRAINT "PK_SCHEDULE" PRIMARY KEY (
   "SCHE_ID"
);

ALTER TABLE "TOPCATEGORY" ADD CONSTRAINT "FK_DOCUMENT_TO_TOPCATEGORY" FOREIGN KEY (
   "DOC_ID"
)
REFERENCES "DOCUMENT" (
   "DOC_ID"
) ON DELETE CASCADE;


ALTER TABLE "PROJMEMLIST" ADD CONSTRAINT "FK_PROJECT_TO_PROJMEMLIST_1" FOREIGN KEY (
   "PROJ_NAME"
)
REFERENCES "PROJECT" (
   "PROJ_NAME"
) ON DELETE CASCADE;

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY (
   "NOTI_ID"
);


ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_PROJMEMLIST_TO_NOTIFICATION_2" FOREIGN KEY (
   "MEM_ID"
)
REFERENCES "PROJMEMLIST" (
   "MEM_ID"
) ON DELETE CASCADE;



ALTER TABLE "FBS" ADD CONSTRAINT "FK_TOPCATEGORY_TO_FBS_1" FOREIGN KEY (
   "TOP_ID"
)
REFERENCES "TOPCATEGORY" (
   "TOP_ID"
) ON DELETE CASCADE;


ALTER TABLE "WBS" ADD CONSTRAINT "FK_FBS_TO_WBS_1" FOREIGN KEY (
   "MID_ID"
)
REFERENCES "FBS" (
   "MID_ID"
) ON DELETE CASCADE;

ALTER TABLE "FIXHISTORY" ADD CONSTRAINT "FK_DOCUMENT_TO_FIXHISTORY_1" FOREIGN KEY (
   "DOC_ID"
)
REFERENCES "DOCUMENT" (
   "DOC_ID"
) ON DELETE CASCADE;

ALTER TABLE "DOCUMENT" ADD CONSTRAINT "FK_PROJECT_TO_DOCUMENT_1" FOREIGN KEY (
   "PROJ_NAME"
)
REFERENCES "PROJECT" (
   "PROJ_NAME"
) ON DELETE CASCADE;

ALTER TABLE "SCHEDULE" ADD CONSTRAINT "FK_PROJMEMLIST_TO_SCHEDULE" FOREIGN KEY (
   "MEM_ID"
)
REFERENCES "PROJMEMLIST" (
   "MEM_ID"
) ON DELETE CASCADE;

---- PROJECT 부분 변경사항 적용 추가본
ALTER TABLE PROJMEMLIST ADD PROJ_DELFLAG CHAR(1) DEFAULT 'N';
CREATE SEQUENCE PROJ_SEQ START WITH 1 INCREMENT BY 1;